### ISSUE TITLE
Set the name of the included build from the include name

### ISSUE THREAD

**Issue by Vampire** [melix/includegit-gradle-plugin#11]
As discussed on Slack, please make it so that

```kts
gitRepositories {
    include("fonts_v3_0") {
        uri.set("git@git.company.com:fonts")
        tag.set("v3.0")
        includedBuild {
            name = "fonts_v3_0"
        }
    }
}
```
could simply be
```kts
gitRepositories {
    include("fonts_v3_0") {
        uri.set("git@git.company.com:fonts")
        tag.set("v3.0")
    }
}
```

**Comment by melix** [comment]
I am actually a bit confused. The checked out directory should be named after the `include` name. So it should be `fonts_v3_0` already.

**Comment by Vampire** [comment]
Now I'm confused too.
I removed the `name = ` lines at the included builds seem to be named like I want it.
But for some reason I had to set the name explicitly. :-/
Sorry for the noise.
