### ISSUE TITLE
[Question] Misconfigured  basic authentication?

### ISSUE THREAD

**Issue by sehenst** [melix/includegit-gradle-plugin#18]
Hi. First of all, thank you for providing thus plugin. Awesome! 👍 🚀 I do think that https://blog.gradle.org/introducing-source-dependencies should have included support for Authentication from the get-go... Anyhow... 😄 

I have two private GitHub repos (let's call them `app` and `lib`). I'm trying to use a feature branch from `app` when building `lib` locally. This is my `settings.gradle` file for the `lib` project:
```
plugins {
    id 'me.champeau.includegit' version '0.1.3'
}

rootProject.name = 'lib'

gitRepositories {
    include('app') {

        authentication {
            basic {
                username = ***
                password = ***
            }
        }

        uri = 'https://github.com/<org>/app.git'
        branch = 'test_includegit'
    }
}
```

This is the result when I reload my Gradle changes:

```

FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\sehenst\IdeaProjects\lib\settings.gradle' line: 8

* What went wrong:
A problem occurred evaluating settings 'lib'.
> Branch or tag test_includegit not found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 505ms
```

I've also tried using the following URI format but I still get the same error.

```
uri = 'git@github.com:<org>/app.git'
```

I'm assuming that I've misconfigured something, but I can't seem to find what. 🤔 Any ideas?

**Comment by melix** [comment]
Does the branch actually exist? It doesn't seem to be an authentication problem.

**Comment by sehenst** [comment]
> Does the branch actually exist? It doesn't seem to be an authentication problem.

Yes, the branch `test_includegit` exists.
![image](https://user-images.githubusercontent.com/60508776/144591841-cfde0e59-7094-4f81-afae-50e7f67ec49b.png)

**Comment by sehenst** [comment]
Hmm. The following works:

```
branch = 'main' // 'test_includegit'
```

**Comment by sehenst** [comment]
Where can I find the log file in order to provide more info?

**Comment by sehenst** [comment]
Before trying to use the remote branch I tried to use a local version of the app repo:

`gradle.properties`
```
local.git.app=C:\\Users\\sehenst\\IdeaProjects\\app
```
This worked as expected.

When I'm now trying to use the remote branch I've commented out the above line. I'm not sure if this information is relevant or not...

**Comment by sehenst** [comment]
Aha! 😄 

I removed the `checkouts` folder, and reloaded my Gradle project. A new `checkouts` folder was created including my `test_includegit` branch. 

Most likely related to how `includegit_gradle_plugin` updates the referenced git repo?

> By default, the plugin will clone the included Git repositories in the checkouts directory of the project. If the repository is already cloned, the plugin will automatically perform an update every 24 hours. Alternatively, you can force it to update by adding -Drefresh.git.repositories to your Gradle command line.

https://melix.github.io/includegit-gradle-plugin/latest/index.html
