### ISSUE TITLE
Cannot obtain value from provider of Gradle property 'auto.include.git.dirs' at configuration time.

### ISSUE THREAD

**Issue by jackzhengpinwen** [melix/includegit-gradle-plugin#26]
the settitng is below:

import me.champeau.gradle.igp.gitRepositories

plugins {
    id("me.champeau.includegit") version "0.1.5"
}

gitRepositories {
    include("jdoctor") {
        uri.set("git@github.com:melix/jdoctor.git")
    }
}

then is error:

Cannot obtain value from provider of Gradle property 'auto.include.git.dirs' at configuration time.
Use a provider returned by 'forUseAtConfigurationTime()' instead.

**Comment by melix** [comment]
What version of Gradle are you using? I recommend upgrading to 7.4+ where `forUseAtConfigurationTime()` is no longer required (and deprecated), which would fix your problem.
