### ISSUE TITLE
Applying project to plugin fails

### ISSUE THREAD

**Issue by apatrida** [melix/includegit-gradle-plugin#7]
Apply this plugin to various projects on Gradle 7.1.1, 6.8, 7.2 and JDK 11, 14 and on Gradle and Kotlin build scripts all results in a failure.

```
An exception occurred applying plugin request [id: 'me.champeau.includegit', version: '0.1.1']
> Failed to apply plugin 'me.champeau.includegit'.
   > class org.gradle.api.internal.project.DefaultProject_Decorated cannot be cast to class org.gradle.api.initialization.Settings (org.gradle.api.internal.project.DefaultProject_Decorated and org.gradle.api.initialization.Settings are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @4e515669)
```

**Comment by melix** [comment]
Thanks for trying out this plugin! As mentioned in the docs, it's a settings plugin, not a project one, so it must be applied to the settings.gradle file.

https://melix.github.io/includegit-gradle-plugin/0.1.1/index.html#_configuration
